### ISSUE TITLE
I have an isse it is discribed in video plz help 

### ISSUE THREAD

**Issue by PureHeartedGuy** [MachineKillin/MSMC#17]
Uploading 19.07.2024_21.36.44_REC.mp4…

**Comment by PureHeartedGuy** [comment]
Uploading 19.07.2024_21.36.44_REC.mp4…

https://screenrec.com/share/24uYCM1hOk

**Comment by PureHeartedGuy** [comment]
@MachineKillin help plz

**Comment by MachineKillin** [comment]
ur antivirus is blocking pip from installing one of the requirements
