### ISSUE TITLE
broken or patched?

### ISSUE THREAD

**Issue by Kilovit** [MachineKillin/MSMC#23]
![image](https://github.com/user-attachments/assets/b15fb5a6-5084-4255-86eb-a3d93b8e56a3)
proxy auto scrape doesnt work
when i use [2] Log, it gives me an error
i dont know how to use combo file and the difference between CUI and LOG
and i think it doesnt use my proxies

**Comment by Kilovit** [comment]
what is that?
![image](https://github.com/user-attachments/assets/4751bf18-8ae2-43ea-a7ac-0e64b1e3d53d)

**Comment by MachineKillin** [comment]
not a code issue its a you issue.
