### ISSUE TITLE
Doesn't find any valid hits.

### ISSUE THREAD

**Issue by cattotaco** [MachineKillin/MSMC#6]
1K combos, and added a few working minecraft accounts in there too, and it didn't register any of them. 0 hits. 
![image](https://github.com/MachineKillin/MSMC/assets/120598479/322c2a0c-575f-412d-950c-5d76e29eee18)

**Comment by cattotaco** [comment]
it just checks the emails, but doesn't register any hits.

**Comment by MachineKillin** [comment]
are you using good proxies?

**Comment by cattotaco** [comment]
Yeah, used proxies and then also tried without proxies. 0 hits

**Comment by MachineKillin** [comment]
if they're free proxies, most likely you will only get 2fa due to microsofts protection. i suggest buying proxies if you want hits lol

**Comment by cattotaco** [comment]
i also used my internet connection, and it still found 0 hits, so idk

**Comment by MachineKillin** [comment]
because you get blocked after sending too many requests from the same ip. like i said buy proxies or you can use a vpn and change your ip manually or use a rotator script for your vpn.
